### ISSUE TITLE
Image Selector collision causes the wrong image to be drawn

### ISSUE THREAD

**Issue by bsouthard-jackhenry** [empira/PDFsharp#191] opened 2024-10-21 18:00 UTC
The attached sample attempts to create a two page document from two different images. However, the first image is displayed on each page. Debugging the issue shows that only one image is stored in the document's image table because the same selector value is calculated for each image. It would seem this would be a rare MD5 hash collision and yet here it happens. Perhaps the selector individuality can be improved beyond simply the hash value.

[Issue.zip](https://github.com/user-attachments/files/17465135/Issue.zip)

**Comment by TH-Soft** [comment] 2024-10-21 18:11
Looks like a duplicate of issue 127. Fix will be in 6.2.0 Preview 2.

**Closed as completed by TH-Soft** 2024-10-21 18:11 UTC
Labels: duplicate, investigation

**Comment by bsouthard-jackhenry** [comment] 2024-10-21 18:46
That's great news. Thanks!

**Comment by bsouthard-jackhenry** [comment] 2024-10-21 19:26
Thanks again, Thomas!

________________________________
