### ISSUE TITLE
PdfReaderException when reading PDF generated from Google Slides

### ISSUE THREAD

**Issue by cbra-nbb** [empira/PDFsharp#196] opened 2024-10-25 06:45 UTC
## Issue
PDFSharp can't read any pdf generated from Google Slides

## Steps to reproduce
1. Go to Google Slides
2. Create new slide (Blank or from templates it doesn't matter)
3. Save as PDF
4. Create a .net 8 Terminal Application
5. Install PDFsharp
6. Add the following code

```
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;

string filePath = "[PATH TO PDF]";

PdfDocumentdocument = [PdfReader.Open](http://pdfreader.open/)(filePath, PdfDocumentOpenMode.Import);

```

7. Run the program

### Expected
PdfReader would be able to read the PDF

### Actual
Program fails with Error: PdfSharp.Pdf.IO.PdfReaderException: 'Name expected.'

### Stacktrace

```
at PdfSharp.Internal.ParserDiagnostics.ThrowParserException(String message)
at PdfSharp.Pdf.IO.Parser.ReadDictionary(PdfDictionary dict, Boolean includeReferences)
at PdfSharp.Pdf.IO.Parser.ReadXRefTableAndTrailer(PdfCrossReferenceTable xrefTable)
at PdfSharp.Pdf.IO.Parser.ReadTrailer()
at PdfSharp.Pdf.IO.PdfReader.OpenFromStream(Stream stream, String password, PdfDocumentOpenMode openMode, PdfPasswordProvider passwordProvider, PdfReaderOptions options)
at PdfSharp.Pdf.IO.PdfReader.OpenFromFile(String path, String password, PdfDocumentOpenMode openMode, PdfPasswordProvider passwordProvider)
at [PdfSharp.Pdf.IO.PdfReader.Open](http://pdfsharp.pdf.io.pdfreader.open/)(String path, String password, PdfDocumentOpenMode openMode, PdfPasswordProvider passwordProvider, PdfReaderOptions options)
at [PdfSharp.Pdf.IO.PdfReader.Open](http://pdfsharp.pdf.io.pdfreader.open/)(String path, PdfDocumentOpenMode openMode, PdfReaderOptions options)
at Program.<Main>$(String[] args) in C:\projects\TesterPrograms\PdfSharpNet8\Program.cs:line 9
```

### Information 
.NET Version: 8
PDFsharp Version: 6.1.1

**Comment by cbra-nbb** [comment] 2024-10-25 06:46
Here is a sample PDF I've created that you can verify with: [GoogleSlidesExamplePDF.pdf](https://github.com/user-attachments/files/17517278/GoogleSlidesExamplePDF.pdf)

**Comment by TH-Soft** [comment] 2024-10-25 08:01
Duplicate of #143

**Closed as completed by TH-Soft** 2024-10-25 08:01 UTC
Labels: duplicate
