### ISSUE TITLE
PdfReader.Open will not open a document

### ISSUE THREAD

**Issue by gtmorrell** [empira/PDFsharp#216] opened 2024-12-12 15:41 UTC
First, thank you for providing such a great tool.  

The code I am having an issue with this code:

// RawFileNames[i] is a list of PDF File Names.

int numberOfPages;
using (PdfDocument existingPdf = PdfReader.Open(RawFileNames[i], PdfDocumentOpenMode.Import))
{
   numberOfPages = existingPdf.PageCount;  
}

The attached file is creating the issue.  
[JMH roof stairs.pdf](https://github.com/user-attachments/files/18113869/JMH.roof.stairs.pdf)

The Unhandled Exception I am getting is:
PdfSharp.Pdf.IO.ObjectNotAvailableException: 'Cannot retrieve stream length.
PDFsharp cannot read this PDF file. If you think your file is a valid PDF file please send it to us so that we can fix this bug in the PDF parser.'

Todd

**Comment by ThomasHoevel** [comment] 2024-12-12 16:00
Have you tried PDFsharp 6.2.0 **Preview 2**?

**Comment by gtmorrell** [comment] 2024-12-12 16:53
I have tried loading it on both 6.1.1 and 6.2.0 and it gives the same exception.  I ran an older version on my software and was able to load the Pdf, but I'm not sure what version it was running on.  I think 6.1.0.  I have updated to .NET 8.0 awhile ago so I can't use 6.1.0

**Comment by ThomasHoevel** [comment] 2024-12-13 08:55
Have you tried PDFsharp 6.2.0 ***Preview 2***?

**Comment by ThomasHoevel** [comment] 2024-12-13 09:41
Corrupted PDF file, not yet supported by PDFsharp.

**Comment by gtmorrell** [comment] 2024-12-13 14:41
Thank you for the quick response. I am asking this next question for clarity.  Why would it work a with previous versions PDFSharp? The PdfSharp DLLs are dated 11/6/23

**Comment by ThomasHoevel** [comment] 2024-12-16 13:06
> Why would it work a with previous versions PDFSharp?

The consistency check was laxer with 6.0.0 and is stricter with 6.1.0 and newer.
Version 6.2.0 Preview 2 can read corrupted files from HP Scan software that cannot be read by version 6.0.0.
Version 6.0.0 can read files from Bluebeam library like your file that cannot be read by 6.2.0 Preview 2.
We'll try to find a way that can read both types of files.

**Comment by ThomasHoevel** [comment] 2024-12-16 13:07
Duplicate of #186

**Closed as completed by ThomasHoevel** 2024-12-16 13:07 UTC
Labels: enhancement, forum
